post_install() {
  # Generated UKI image is named grubaa64.efi to match the hardcoded paths in https://github.com/BigfootACA/simple-init/blob/master/src/boot/efi_path.c
  mkdir -p "/boot/efi/EFI/manjaro"
}

post_upgrade() {
  if findmnt --fstab -uno SOURCE /boot/efi &>/dev/null && ! mountpoint -q /boot/efi; then
    echo "WARNING: /boot/efi appears to be a separate partition but is not mounted."
  fi
}

post_remove() {
  rm -f /boot/initramfs-linux.img
}
