name: buildarmpkg
on:
  workflow_dispatch:
  push:

concurrency:
  group: ${{ github.repository }}-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  package:
    runs-on: ubuntu-22.04
    steps:
      -
        uses: actions/checkout@v4
        with:
          fetch-depth: '1'
      - 
        id: time
        uses: boredland/get-time-action@2.0.0
        with:
          format: 'YYYYMMDD'
      -
        name: Makepkg Build and Check
        id: makepkg
        uses: rodriguezst/pkgbuild-arm64-action@v1
        with:
          makepkgArgs: -s
      - 
        name: Copy Package Files
        run: |
          mkdir -p ./artifacts
          find . -type f -name '*.pkg.tar.*' -exec cp '{}' ./artifacts/ ';'
      -
        name: Release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.time.outputs.time }}
          name: ${{ steps.time.outputs.time }}
          draft: false
          prerelease: false
          files: |
            ./artifacts/*.pkg.tar.*
